### ISSUE TITLE
[Request] Put it on the Single Player Screen too

### ISSUE THREAD

**Issue by kreezxil** [TechnicianLP/ReAuth#11]
I know this seems pointless but actually it isn't because on an opened to lan world it would come in handy the same way.

**Comment by ZandercraftGames** [comment]
Good idea.

**Comment by TechnicianLP** [comment]
That Button would have no advantage to most Players.
Connecting to LAN Worlds is done in the Multiplayer Menu anyways, if youre talking about changing the Hosting Players Account/Name a detour to the Multiplayer is still faster than restarting.
