### ISSUE TITLE
[Request/Suggestion] Config to disable update checker

### ISSUE THREAD

**Issue by DemonfangArun** [TechnicianLP/ReAuth#12]
Curse already does a good enough job of this. I would like to request that a config option be added to disable phoning home. I have timed it and as I've shut down update checkers, analytics, etc... the time to connect to a server has dramatically dropped.

https://github.com/TechnicianLP/ReAuth/issues/4
This also disturbs me. I don't want to be having to update my pack every 6 months, or the 1.12 version stops being maintained, and I suddenly have to go back and issue a random update to a pack to remove this mod. FWIW Gunner76th is correct, you shouldn't be forcing changes on users.

**Comment by DWX12** [comment]
I would like to also have this request. When each and every mod wants to check for updates, it creates a greater load on systems than it needs to. If anything, atleast have it plug into Mojang's snooper settings and toggle the checker off if the setting is turned off.

This mod is so very handy, specifically for large packs with long loading times. I thank you for creating this mod that helps out so many, just looking for more control over it.

**Comment by SirAron111** [comment]
Ye that would be a good thing

**Comment by ProsperCraft** [comment]
Yes, please add this when you update...all of the mod update checking adds to load time, and it is not needed when players are playing a modpack where the updates are controlled by the mod author.

**Comment by TechnicianLP** [comment]
The UpdateChecker has been fully moved over to the Forge integrated System in the 1.14/1.15 Versions; Other Versions will follow Suit once an Update happens.
As for the forcing of Updates i have to apologize
