### ISSUE TITLE
Question: Is the removal of this mod important on Servers Mod folder?

### ISSUE THREAD

**Issue by SirAron111** [TechnicianLP/ReAuth#14]
I wanted to know if it’s Important that the mod is removed from the Servers mod folder. Or if I can keep it in and it will just not be actively loaded by the Server start like other client side mods. Or would it mess-up the server if it’s there?

The explanation (The Mod is Clientside only - it will not work in servers mods folder) only tells me it doesn’t work but not if it’s just disabled or stops the server from working.

**Comment by TechnicianLP** [comment]
Forge will load the mod but not initialize it - ie it uses up a tiny bit of ram but will not do anything else; the server will work just normal
