### ISSUE TITLE
[Request] Fabric Support

### ISSUE THREAD

**Issue by pointydev** [TechnicianLP/ReAuth#15]
Hey there,

Any chance we could see a [Fabric](https://fabricmc.net/) port of this mod?

Thanks,
Elliott

**Comment by icha-senpai** [comment]
I'd like this for fabric aswell

**Comment by aidan-mundy** [comment]
Just would like to bump the request for fabric support. It is becoming more and more relevant, especially with the replay od being on fabric now

**Comment by JayJay1989** [comment]
If i have some spare time today, i will port it to fabric.

**Comment by TechnicianLP** [comment]
Fabric is now avaialble for Fabric on 1.16 https://www.curseforge.com/minecraft/mc-mods/reauth/files/3007486
