### ISSUE TITLE
[Issue] Invalid Token

### ISSUE THREAD

**Issue by ItsNora** [TechnicianLP/ReAuth#16]
So, over the last month to two months, while logging in using reauth (to save time) the red X is continuously there. No matter what. I have changed the password on my account, edited the config password, everything. But nothing has worked. I consistently get an Invalid Token thrown at me.

This has occured on more than one launcher as well

**Comment by TechnicianLP** [comment]
Missed this Issues - Sorry
Would you be kind enough to provide a console printout of the exception?
Can you play on Servers?
