### ISSUE TITLE
[Suggestion] 1.14.4 ?

### ISSUE THREAD

**Issue by Wissi** [TechnicianLP/ReAuth#17]
Any chance you might be porting this over to 1.14.4 soon?

We really need your awesome work.

Thanks.

**Comment by kreezxil** [comment]
@TechnicianLP I see you logged on to CurseForge 3 days ago. I'm wissi on this one. We could really use this in 1.14.4. 

If you don't have plans to port this for whatever reason, can you loosen the license on CurseForge to one that is open so that the community can port it for you?

**Comment by TechnicianLP** [comment]
I am still working on the rewrite, yet with work and ever more issues and bugs coming up in said rewrite it has taken significantly longer than reasonable - i will try to do a 1:1 port in the next few days though - the rewrite will have to wait until it is ready

**Comment by alexis-evelyn** [comment]
1.15 just came out today though, but not every server has updated to 1.15 yet. Some like Performium have updated within a few hours of 1.15's release.

**Comment by kreezxil** [comment]
@alexis-evelyn stating that in a tracker for modding that uses FORGE ... **makes your statement** __inaccurate__

Forge for 1.15 is not out.

see here at https://files.minecraftforge.net

**Comment by Axieum** [comment]
Hey @Wissi, I just released [Auth Me](github.com/Axieum/AuthMe) a `1.14.4` equivalent to **ReAuth** by TechnicianLP. Expect a `1.15` version soon.

**Comment by TechnicianLP** [comment]
a Version for 1.14.4 and 1.15 is available now at https://www.curseforge.com/minecraft/mc-mods/reauth/files/2854743
