### ISSUE TITLE
Proper license for OSS

### ISSUE THREAD

**Issue by S-B99** [TechnicianLP/ReAuth#19]
Hi, this appears to be a well maintained and well written project. Would you mind putting this under an open source license so people can use it in their projects? 

If not, would I have permission to use it in my open source and completely free mod? (S-B99/KAMI)

**Comment by TechnicianLP** [comment]
The README.md states what you are looking for: "License: All Rights Reserved"
This Mod is visible source, not open source. No you dont have Permission to include my code in your Mod.
