### ISSUE TITLE
Stops mouse from working inside of minecraft

### ISSUE THREAD

**Issue by Isaacw24** [TechnicianLP/ReAuth#26]
my mouse no longer works, for looking around it is in a fixed position and minecraft is in focus

**Comment by TechnicianLP** [comment]
Could you please state your Operating System, Minecraft Version, ReAuth Version used Mod Loader (Forge or Fabric) and a complete list of used mods?

**Comment by Isaacw24** [comment]
Sorry, it turns out it was tweakeroo, but as soon as i downloaded it happened, thanks!
