### ISSUE TITLE
Email Lenth Too Short

### ISSUE THREAD

**Issue by XerShade** [TechnicianLP/ReAuth#3]
The maxium length on the email field for logging in is too short. The config editor is fine but I can't actually login with my long email.

**Comment by TechnicianLP** [comment]
Will get fixed in the next version! Minecraft lets Textboxes have a maximum lenght of 32 by default (which indeed is a bit low) thanks for pointing this out!

**Comment by TechnicianLP** [comment]
(The next version may take a wile because i'm currently reorganizing my computer)

**Comment by XerShade** [comment]
Ah. Well the lengths of the config box and the one used to login dont match. I can type my email into the configs box but not the one on the login page.

Also no rush, great mod and this is just a small oversight. One restart to switch to my camera account and back is better than two.

**Comment by TechnicianLP** [comment]
I increased the maximum length of both boxes to 512 in version 3.4.
Let me know if you have any issues!
