### ISSUE TITLE
Microsoft login not working in 1.7.10

### ISSUE THREAD

**Issue by brendenspencer** [TechnicianLP/ReAuth#44]
when you try to use reauth in 1.7.10 it loads the website but after you login it says login failed

**Comment by TechnicianLP** [comment]
Would you be able to provide a logfile?

**Comment by brendenspencer** [comment]
[2022-06-06-3.log.gz](https://github.com/TechnicianLP/ReAuth/files/8852967/2022-06-06-3.log.gz)
