### ISSUE TITLE
[1.19] Crash due to breaking change in Forge?

### ISSUE THREAD

**Issue by ProsperCraft** [TechnicianLP/ReAuth#47]
https://gist.githubusercontent.com/ProsperCraft/d96c46637d3305e85abafa814e3a2618/raw/cd9153ff60cd3c4a76cab265c34c45c299c584a1/gistfile1.txt
ReAuth-1.19-Forge-4.0.4
forge-1.19-41.0.110

**Comment by TechnicianLP** [comment]
Looks to be caused by breaking changes in Forge - A fixed version (4.0.5) is currently processing on Curseforge and will be available shortly
