### ISSUE TITLE
Not working correctly on 1.16.5

### ISSUE THREAD

**Issue by Enrico9431** [TechnicianLP/ReAuth#49]
The only thing that happens when I click the button is this lighted panel
https://imgur.com/a/ub4tjMY

**Comment by TechnicianLP** [comment]
Please provide a logfile.

**Comment by Enrico9431** [comment]
Here are my latest general log files if that's what you want as I wouldn't know what kind of log file you otherwise want.
Reason that I'm sending multiple is that I don't remember restarting my game

[latest.log](https://github.com/TechnicianLP/ReAuth/files/9330330/latest.log)
[2022-08-12-1.log.gz](https://github.com/TechnicianLP/ReAuth/files/9330331/2022-08-12-1.log.gz)
[2022-08-11-1.log.gz](https://github.com/TechnicianLP/ReAuth/files/9330332/2022-08-11-1.log.gz)
[2022-08-11-2.log.gz](https://github.com/TechnicianLP/ReAuth/files/9330333/2022-08-11-2.log.gz)

**Comment by DaleHat** [comment]
i have the same issue
[latest.log](https://github.com/TechnicianLP/ReAuth/files/9378226/latest.log)

**Comment by 4rz0** [comment]
I have the same problem.

Turns out the GUI is there, just invisible.
I randomly clicked around and my browser opened with the login prompt.
Login then worked fine.

**Comment by TechnicianLP** [comment]
Thanks for the hint with Optifine - Looks like Optifine has a Bug and doesnt support one of Forges features correctly.
A Workaround has been added to v4.0.7 which should make it possible to use ReAuth with Optifine
