### ISSUE TITLE
ely.by

### ISSUE THREAD

**Issue by SvEgiiVEteR** [TechnicianLP/ReAuth#5]
does not work with this library authlib-1.5.24 from http://ely.by/

**Comment by TechnicianLP** [comment]
Define "does not work" ... (i wont download/use some random authlib)

**Comment by SvEgiiVEteR** [comment]
https://gist.github.com/a9438f4e676e2bfdbe30f3671bc755f9

**Comment by TechnicianLP** [comment]
ok im getting this a the response for the authentification request: https://hastebin.com/hahataquqe.json looks like youll have to report it to them ... they changed the server to which you authenticate to but forgot to setup the service responsible for it

**Comment by SvEgiiVEteR** [comment]
thank you, to tell
