### ISSUE TITLE
Site can't be reached, localhost server down?

### ISSUE THREAD

**Issue by genesy** [TechnicianLP/ReAuth#50]
v4.0.4 for 1.18
whenever i successfully login the redirect url http://127.0.0.1:52371/ is down for me so the mod just waits indefinitely..

**Comment by Spongman** [comment]
I'm seeing the same thing.
ATM7 1.0.8 modpack
ReAuth 4.0.4

**Comment by invalidtask** [comment]
Same issue for 1.18.2

**Comment by Nekosity12** [comment]
Also having this issue on FTB Stoneblock 3 Alpha 1.20

**Comment by MaienM** [comment]
The "any device" flow still works for me, try using that as a workaround.

**Comment by TechnicianLP** [comment]
Has been fixed for Version 4.0.6. Sorry for the long wait
