### ISSUE TITLE
Login button / ReLogin button

### ISSUE THREAD

**Issue by Lyrad8791** [TechnicianLP/ReAuth#7]
This is missing. It was stated a fucking year ago that it would be able to be used with custom main menu. It has been in several modpacks and worked. Now, It doesn't work in any fucking pack what so ever. There is no info anywhere as to how to make the button appear, and it is the only god damned mod on the fucking internet that does what is needed to reloggin to minecraft without closing the fucking game completely.

Now, Would you kindly inform myself and everyone else how to fix this bullshit issue that has been going on? Would you post some fucking info on how to bypass this issue if it comes up? Hell, put in a goddamned hotkey so it can be used without a button itself even.

I hope you get to this and fix this soon, as I am tired of reloading every fucking modpack I play after a few hours because I have to reloggin to minecraft auth servers.

**Comment by TechnicianLP** [comment]
Support for CMM is added by adding an invisible button to the mainmenu to be wrapped by CMM (Button-ID 17325)

**Comment by ResqDiver1317** [comment]
Sorry for posting on a closed issue, but I have scoured CMM's info and their documentation is severely lacking so I was wondering if anyone could advise me on how to actually go about adding this invisible button/wrapper?
Thanks in advance for any advice that can be given!
