### ISSUE TITLE
[1.12.2] Classnames could not be fetched!

### ISSUE THREAD

**Issue by SamboyCoding** [TechnicianLP/ReAuth#9]
So... I think I broke it. I can't see this issue ANYWHERE else, but somehow I managed to get the mod to throw this crash report
[crash-2018-05-06_13.06.39-client.txt](https://github.com/TechnicianLP/ReAuth/files/1977591/crash-2018-05-06_13.06.39-client.txt). Looking through the code this is quite obviously thrown [here](https://github.com/TechnicianLP/ReAuth/blob/master/src/main/java/reauth/Secure.java#L58). I don't quite know how this could be happening, but if you could take a look that would be greatly appreciated, thanks.

Forge Version: 14.23.3.2678
Minecraft Version: 1.12.2

**Comment by SamboyCoding** [comment]
Maybe it would be possible to get an insight into how this is happening by wrapping the IOE in the RuntimeException that's thrown so it prints info for that too?

**Comment by TechnicianLP** [comment]
Is this issue happening persistently? If yes could you please try launching with movingworld removed?
I dont think it will be as simple as wrapping the Exception as this looks like a pretty weird classloading issue

**Comment by SamboyCoding** [comment]
As far as i can tell yes. It happens every time I start the game, at the end of pre-init. I will test now sans movingworld.

**Comment by SamboyCoding** [comment]
[crash report without movingworld](https://github.com/TechnicianLP/ReAuth/files/1992850/crash-2018-05-10_19.41.28-client.txt) - it's exactly the same

**Comment by TechnicianLP** [comment]
I wrapped the exception in 3.6.0 (available shortly for 1.12)

**Comment by SamboyCoding** [comment]
Ok, i'll see what i can do for you.

**Comment by SamboyCoding** [comment]
[crash report](https://github.com/TechnicianLP/ReAuth/files/1998290/crash-2018-05-13_10.11.23-client.txt) Looks like it's not liking that ClassPath.from, which suggests that something is changing the classloader. Maybe the next step is to print out what that classloader is?

**Comment by TechnicianLP** [comment]
Please add this debug-mod to your mods-folder and send me the full log: https://minecraft.curseforge.com/projects/reauth/files/2562006/download

**Comment by TechnicianLP** [comment]
Good to know the method can't handle wildcard paths - yet it's not really my fault.
As this is the only known case so far you could fix your launcher to include the specific files. (or try updating the guava library)
Yet that method is going to go away in a future version anyways
